### ISSUE TITLE
Handle password resets

### ISSUE THREAD

**Issue by jonuy** [DoSomething/northstar#128]
Scenarios to consider:
- password reset on Drupal should also get reset in Northstar
- password reset from mobile app for a user with an email address
- password reset from mobile app for a user with only a mobile number

This is likely a big, hairy build so just offering a place to start logging the conversations on it.

**Comment by aaronschachter** [comment]
Refs discussions in #117

**Comment by DFurnes** [comment]
Passwords reset on the Drupal site _should_ be getting updated in Northstar [here](https://github.com/DoSomething/phoenix/blob/a7aa77fc99c14d53aa52158be0a5b0f861fedc88/lib/modules/dosomething/dosomething_user/dosomething_user.module#L461-L468). We don't currently push updates made in Northstar back to the Drupal site, although that's something we can hopefully sidestep by checking Phoenix logins against Northstar rather than the local database.

**Comment by DFurnes** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(13) As an engineer, I want the forgot password flow to go through northstar so that I can deploy northstar auth to production.](https://trello.com/c/3ohW8uGe/66-13-as-an-engineer-i-want-the-forgot-password-flow-to-go-through-northstar-so-that-i-can-deploy-northstar-auth-to-production)

**Comment by DFurnes** [comment]
We want to implement password resets using Laravel's built-in [password reset functionality](https://laravel.com/docs/5.3/passwords). Since Quicksilver API is not ready, we'll just send plain-text password reset emails for now (similar to how we do things in Gladiator).

**Comment by DFurnes** [comment]
Oh wow we totally do this.
