### ISSUE TITLE
Fix error message on failed login for user that doesn't exist

### ISSUE THREAD

**Issue by jonuy** [DoSomething/northstar#188]
Currently, when the user doesn't exist and you try to login, you get a 404 error with the message "User is not registered."

Quoting Sergii here, this is a "user enumeration" security vulnerability.

We should make the response more generic to something along the lines of "your user name and password are not correct." Or whatever it is that we already send when a login fails for a user that _does_ actually exist.

**Comment by aaronschachter** [comment]
When we send a login for a user that DOES exist, the message reads "Incorrect password", so we don't want to use that. Actually that text might be considered a security vulnerability too, as it suggests that an email does exist.

On the web, the copy reads: "Sorry, unrecognized username or password." Which is exactly not great because we don't make use of Drupal's default `username` property.

How about just "Invalid username/password" ? To use for both scenarios when a user email doesn't exist, or the password is incorrect.
