### ISSUE TITLE
update user PUT request will not accept array as value for `parse_installation_ids` key

### ISSUE THREAD

**Issue by tongxiang** [DoSomething/northstar#250]
Discussed this with @jonuy, while working on [this issue](https://github.com/DoSomething/LetsDoThis-iOS/issues/45) in the iOS app. We want the `PUT /users/_id/<user_id>` update user endpoint to be able to accept either a string or an array, since a user can have multiple `parse_installation_ids` associated with her account. (She could have logged into her account on different devices.) 

However, currently this endpoint can only accept a string (though, perhaps it expects a comma-separated string?). Error returned by endpoint: 

```
{
  "error": {
    "code": 500,
    "message": "explode() expects parameter 2 to be string, array given"
  },
  "debug": {
    "file": "/var/www/northstar/releases/20151113151307/app/Models/User.php",
    "line": 99
  }
}
```
Whew! And that's my last DS issue!

**Comment by jonuy** [comment]
:bow:

**Comment by DFurnes** [comment]
Ahh, yep. It expects a comma-separated string (the values of which are appended to the user's parse installation IDs in their profile).

**Comment by DFurnes** [comment]
@jonuy Let me know if you have thoughts on a more intuitive way of handling this, since it _does_ seem to kinda break typical REST assumptions.

**Comment by jonuy** [comment]
@DFurnes Hm I'm remembering now that I actually thought we did try to handle this in the [setter](https://github.com/DoSomething/northstar/blob/dev/app/Models/User.php#L98).

```
public function setParseInstallationIdsAttribute($value)
{
    $ids = is_array($value) ? $value : array_map('trim', explode(',', $value));
    $this->push('parse_installation_ids', $ids, true);
}
```

If I'm understanding this correctly, shouldn't this allow for either an array or csv string to be passed?

**Comment by DFurnes** [comment]
Hmm, it would appear so! I haven't tested that, but certainly seems good. I do still think its a little unexpected that that doesn't replace the value of the field (like setting something in an `update` body otherwise would), but instead appends to the array.

But seems like this is good enough to close for now? :hammer:

**Comment by jonuy** [comment]
Yea, replace vs appends ... would the expected way to do it just involve the client doing a GET to find out what the current array is and then appending it itself before sending a PUT?

I think interests has a similar behavior and I'm pretty sure we had it just append because we couldn't rely on the different platforms (Phoenix, Mobile App, CGG, etc) to all do a GET first before sending.

Either way, I'm not sure if we should close until actually manually testing it or setting up a test for it? Tong seemed to suggest that it wasn't working in its intended way.

**Comment by DFurnes** [comment]
I remember talking it through IRL and I _think_ we figured it out, but no harm double-checking. For an alternative solution to appending/replacing, it feels like RESTfully these should maybe be a sub-resource that you can `POST` or `DELETE` (that then just gets embedded in the user response object). Worth considering if we take time to refactor down the road.

**Comment by aaronschachter** [comment]
Finally getting around to looking at this.  Related related issue/ask for this one is updating API documentation to clarify that we can store multiple id's via:
> It expects a comma-separated string (the values of which are appended to the user's parse installation IDs in their profile).

Will let yous know whether I run into same issues.

**Comment by DFurnes** [comment]
@aaronschachter Updated documentation! :pencil2:

**Comment by DFurnes** [comment]
Just double-checked this locally, and seems to work as expected:

If user has `parse_installation_ids: ['1']`

1. Sending a plain string `2` will append to the array: `parse_installation_ids: ['1', '2']`
2. Sending a CSV string `3,4` will append to the array: `parse_installation_ids: ['1', '3', '4']`
3. Sending an array `['5', '6']` will append each string to the array: `parse_installation_ids: ['1', '5', '6']`

Going to close this, but feel free to re-open if you run into issues.
