### ISSUE TITLE
Standardized source values

### ISSUE THREAD

**Issue by DFurnes** [DoSomething/northstar#321]
Currently, a user could use the mobile app API key and tamper with their `auth/register` request to set a nonsense source value. We should consider standardizing this as an enum value with a set of pre-defined "acceptable sources" somewhere.

:runner: **Stretch goal:** It could also be interesting to look into having the source inferred from the API key for the request (e.g. if a request is made with the `LetsDoThis` API key, set that in the "source" field automatically).

**Comment by jessleenyc** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [As a dev, I want to standardize source value and have the source inferred from the API key for each request so that users can't tamper with the auth/register request.](https://trello.com/c/8snYuiUe/133-as-a-dev-i-want-to-standardize-source-value-and-have-the-source-inferred-from-the-api-key-for-each-request-so-that-users-can-t-t)
