### ISSUE TITLE
Improvements to fetching multiple results

### ISSUE THREAD

**Issue by DFurnes** [DoSomething/northstar#325]
Currently, applications that need to fetch multiple users are using the "filter" query parameter on the users resource, e.g. `users/?filter[_id]=123&filter[_id]=124`. This is helpful for limiting the number of trips that need to be made to the server, but unfortunately hurts our ability to cache individual requests.

We've also run into issues where the query string is too long if we try to fetch too many items per request (and like the whole HTTP request fails), which is just silly.

We should :zap: :cloud: if there are better solutions for this!

**Comment by jessleenyc** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [As a dev, I want to make improvement to fetching multiple requets so that we dont' run into issues like when the query string is too long when we fetch too many items.](https://trello.com/c/mURHldec/135-as-a-dev-i-want-to-make-improvement-to-fetching-multiple-requets-so-that-we-dont-run-into-issues-like-when-the-query-string-is-t)
