### ISSUE TITLE
Prototype GraphQL endpoints?

### ISSUE THREAD

**Issue by DFurnes** [DoSomething/northstar#326]
This is totally wild and not on the roadmap, but it might be worthwhile to prototype using [GraphQL](http://graphql.org) to allow clients to make more specific requests for the type of information they want to receive.

This could help mobile apps by letting them request only the specific fields they need (so they'd get smaller payloads in the final response), and it seems like it'd also have applications for [better caching](http://facebook.github.io/relay/docs/thinking-in-graphql.html#client-caching) when requesting multiple items.

**Comment by jessleenyc** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [As a dev, I want to prototype GraphQL endpoints so that clients can make more specific requets for the type of info they want to receive.](https://trello.com/c/hTEYT9Q4/136-as-a-dev-i-want-to-prototype-graphql-endpoints-so-that-clients-can-make-more-specific-requets-for-the-type-of-info-they-want-to-)

**Comment by DFurnes** [comment]
Hey hey [graphql.dosomething.org](graphql.dosomething.org)!
