### ISSUE TITLE
Audit log for user profile changes

### ISSUE THREAD

**Issue by DFurnes** [DoSomething/northstar#335]
It'd be nice to have an audit log of user profile changes (probably in Redis?), so we can track when fields were changed and by which application. This would be helpful for debugging, and also a nice customer support/security feature (i.e. "When did I change my password?").

**Comment by jessleenyc** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [As a dev, I want to log user profile changes so that we can track when fields are changed and learn about user/provide customer support.](https://trello.com/c/fz663kj2/137-as-a-dev-i-want-to-log-user-profile-changes-so-that-we-can-track-when-fields-are-changed-and-learn-about-user-provide-customer-s)
