### ISSUE TITLE
Should we remove upsert behavior from the POST users endpoint?

### ISSUE THREAD

**Issue by DFurnes** [DoSomething/northstar#383]
I'd like to consider removing "upsert" behavior from the `POST users/` endpoint altogether for a potential v2, since it seems like an easy way to shoot ourselves in the foot and mangle data that we don't intend to (aside from syncing users, where it's pretty necessary).

References #361.

**Comment by jessleenyc** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [As a dev, I want to remove upsert behavior from the POST users endpoint so that we don't accidentally mangle data we don't intend to.](https://trello.com/c/aoEHquMc/142-as-a-dev-i-want-to-remove-upsert-behavior-from-the-post-users-endpoint-so-that-we-don-t-accidentally-mangle-data-we-don-t-intend)
