### ISSUE TITLE
Better testing tools for gateway

### ISSUE THREAD

**Issue by DFurnes** [DoSomething/northstar#395]
Right now we fully mock our HTTP clients (e.g. `\Northstar\Services\Phoenix`) so they always return a consistent response in test suites. We should look into using [Guzzle's testing helpers](http://docs.guzzlephp.org/en/latest/testing.html) so we can still have confidence that the calls to Guzzle are working correctly when we update the library.

**Comment by jessleenyc** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [As a dev, I want better testing for guzzle clients so that we are confident the calls to guzzle are working correctly when we update the library.](https://trello.com/c/ORSSFyHL/144-as-a-dev-i-want-better-testing-for-guzzle-clients-so-that-we-are-confident-the-calls-to-guzzle-are-working-correctly-when-we-upd)

**Comment by DFurnes** [comment]
This wasn't a thing when I made this issue, but maybe we should use Gateway clients in Northstar!?

![](http://www.reactiongifs.com/r/2013/10/tim-and-eric-mind-blown.gif)
