### ISSUE TITLE
Potentially breaking changes on NS QA??

### ISSUE THREAD

**Issue by angaither** [DoSomething/northstar#408]
@sbsmith86 and I have tried logging into gladiator (locally and on staging) 
and each time we get a "whoops northstar returned an error for that request" 

It seems like [prod is on an older version](https://github.com/DoSomething/northstar/commit/c0bf22e72088a6199ca714bee0ad379f02cef7ad) than [qa/thor](https://github.com/DoSomething/northstar/commit/e6255f2fbc5cd162587867adb2457c07bfd81b51) has something changed? NS is returning a `403` for all login attempts there

**Comment by DFurnes** [comment]
It'd be helpful to see the actual error response. If you're sending an `Accepts: application/json` header with your API requests, it should return a more helpful message (it'd make sense in the future to perhaps differentiate response by route, rather than by headers, so this doesn't happen).

My guess is that those servers were using the old `abc4324` seeded API keys, which I had removed from Northstar QA a few weeks ago since that'd allow anyone that looked at our old seed data to access/modify QA account details.

**Comment by angaither** [comment]
@DFurnes AHHA. you would be correct, using old keys. Alright so we need to set up new keys for this app on aurora QA?

**Comment by DFurnes** [comment]
@angaither @sbsmith86 Yep! You can check out [existing clients](https://qa-aurora.dosomething.org/clients) on Aurora QA, and create a new one with the "New Client" button there! To work with Gladiator, I'm pretty sure it should have the `admin` and `user` scopes.

**Comment by angaither** [comment]
@DFurnes rare footage ron swanson filling out this form. 
![](https://cl.ly/3p0E1D1w0S09/Screen%20Recording%202016-08-23%20at%2010.46%20AM.gif)

Also I'm very dense and don't know what to [update the `.env` with?](https://github.com/DoSomething/gladiator/blob/master/.env.example#L23)
Do we also need to [update calls from gladiator?](https://github.com/DoSomething/gladiator/blob/cc1d566357d62befe88557e3cecb45ec2cf4fd38/app/Services/Northstar/Northstar.php#L17) 

Am I looking in the [wrong place?](https://github.com/DoSomething/northstar/blob/dev/documentation/authentication.md)

**Comment by DFurnes** [comment]
> Also I'm very dense and don't know what to [update the `.env` with?](https://github.com/DoSomething/gladiator/blob/master/.env.example#L23)
Do we also need to [update calls from gladiator?](https://github.com/DoSomething/gladiator/blob/cc1d566357d62befe88557e3cecb45ec2cf4fd38/app/Services/Northstar/Northstar.php#L17) 

Yeah, it's not really documented. Since Gladiator doesn't use OAuth, you can just place the client secret into the `NORTHSTAR_API_KEY` environment variable.

> Am I looking in the [wrong place?](https://github.com/DoSomething/northstar/blob/dev/documentation/authentication.md)

There's a little documentation on the legacy auth mechanisms [here](https://github.com/DoSomething/northstar/blob/dev/documentation/authentication_legacy.md), but definitely let me know if I can help out. Ideally we don't use it for new builds, so I haven't focused much on making sure that documentation is all that great.

**Comment by angaither** [comment]
@DFurnes no worries, that makes sense. THANK YOUUUUU for halping. it is back to working meow! 🙇 🙇 🙇
