### ISSUE TITLE
Research: standardize getting user data from northstar

### ISSUE THREAD

**Issue by jessleenyc** [DoSomething/northstar#422]
_TASK_
Research the most efficient way the openid connect drupal module expects data.

_ADDITIONAL INFO_
@DFurnes please add some context for me! and future people who might read this ticket.

**Comment by DFurnes** [comment]
Context: We want Northstar to be our "single source of truth" for user data, so there needs to be a way for Phoenix and Northstar to communicate that when a user logs in. Since we're prototyping using [OpenID Connect](https://openidconnect.net) to handle the authorization process, luckily these problems have been solved before!

So by default, the Drupal [OpenID Connect module](https://www.drupal.org/project/openid_connect) expects the user's profile ID to be provided in the `sub` claim of the token, which is [what we do](https://github.com/DoSomething/northstar/blob/dev/documentation/authentication.md#access-tokens) already. It expects everything else to be accessible from a ["user info" endpoint](http://openid.net/specs/openid-connect-core-1_0.html#UserInfo), with standardized field names (e.g. `given_name` for first name). We don't have this yet, but it seems pretty reasonable to implement.
