### ISSUE TITLE
API gateway (e.g. "the one URL to rule them all")

### ISSUE THREAD

**Issue by angaither** [DoSomething/northstar#49]
Create an `api.dosomething.org` or something like that and have that handle rules to send things to either the DS drupal app, or northstar.

Can fastly handle these varnish rules?
- User requests would get sent to northstar
- Content requests send to drupal

cc @blisteringherb

**Comment by DFurnes** [comment]
It might be too enterprisey, but it'd be worth looking into something like [Kong](https://getkong.org/) for this (to handle sharing authentication/tokens between services).

**Comment by jessleenyc** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [As a dev, I want to crete an API gateway so that it can handle rules to send things to our different apps.](https://trello.com/c/7IVQOlXO/134-as-a-dev-i-want-to-crete-an-api-gateway-so-that-it-can-handle-rules-to-send-things-to-our-different-apps)

**Comment by DFurnes** [comment]
This can be closed. If we decide to go forward with it, this is the purpose our [GraphQL service](https://graphql.dosomething.org) would fill.
