### ISSUE TITLE
Version Number

### ISSUE THREAD

**Issue by DeeZone** [DoSomething/northstar#58]
Based on the wiki - https://github.com/DoSomething/northstar/wiki/Spec the version number is indicated as "1" in `https://api.dosomething.org/1/`. This is a potential source of confusion that is often addressed by denoting the version number with a "v". 

Example:
```
https://api.dosomething.org/v1/
```

**Comment by weerd** [comment]
As a side note... I finished reading "Build APIs You Won't Hate" and apparently the ideal way to go about defining versioning to actually get closer to HATEAOS is to define version within the header content, so that when versions change, the paths for devs don't break. Apparently this is what GitHub does. It's a nice thought, but not sure if Drupal accommodates for it though :\

**Comment by angaither** [comment]
@weerd yeah, there's some interesting debates about header version, vs url versioning.
this is laravel silly, not drupal! ;)
but the client can still use an old version in their url, as we require them to specify which version they use.

**Comment by weerd** [comment]
Doh! Sorry, I'm in Drupal world right now :( Yeah, in the book it talks about some of the benefits for header versioning and seems to outweigh url versioning, but he also goes on to indicate that there really isn't any silver bullet solution. While one might be more ideal, it may increase complexity to get there, etc.
